from dataclasses import dataclass
from typing import Optional


@dataclass
class PreprocessingData:
    """
    Data paths generated by Preprocess Step.
    """

    train_path: Optional[str] = None
    test_path: Optional[str] = None
    batch_path: Optional[str] = None